### ISSUE TITLE
main.go just hangs forever?

### ISSUE THREAD

**Issue by blacktop** [appropriate/go-virtualboxclient#4]
``` bash
2016/05/13 20:13:29 <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body xmlns="http://schemas.xmlsoap.org/soap/envelope/"><IWebsessionManager_logon xmlns="http://www.virtualbox.org/">
```

Am I doing something wrong?

**Comment by blacktop** [comment]
running with sudo gets me: 

``` bash
2016/05/13 20:46:12 Unable to log on to vboxwebsrv:
exit status 1
```

So it is using VBoxAuth do I need to create a user/pass first?

**Comment by blacktop** [comment]
`VBoxManage setproperty websrvauthlibrary null`

This fixed it. Sorry I should have read more before 'issueing'

Cheers

**Comment by md5** [comment]
@blacktop No problem!

This code isn't much more than a (weak) proof of concept at this point and `main.go` is clearly not very useful other than testing that you can connect to the API.

The code in #2 and #3 do a lot to improve the functionality of this library, but unfortunately I haven't had enough time to review them properly and I think @clintonskitson got discouraged about getting them merged.

**Comment by blacktop** [comment]
@md5 I really hope you find the time, this is a great project and I have a great need for it.

@clintonskitson have you tested your Pull Requests?  Do they work?

**Comment by clintkitson** [comment]
@blacktop The PR there represents the basis of REX-Ray/libStorage. Works as expected.

https://github.com/emccode/libstorage/blob/master/glide.yaml#L20-L22

**Comment by blacktop** [comment]
@clintonskitson oh damn !!! I knew **emccode** sounded familiar. REX-Ray is awesome !!

**Comment by clintkitson** [comment]
Thanks @blacktop, glad you like it  and thanks @md5 for getting this one started.

**Comment by clintkitson** [comment]
btw.. you may find the implementation example of this package useful in our driver.

https://github.com/emccode/libstorage/blob/master/drivers/storage/vbox/storage/vbox_storage.go

**Comment by md5** [comment]
@blacktop To be honest, it's increasingly unlikely that I'll be able to work much more on this code.

Given that Docker is moving away from VirtualBox as their platform for running `boot2docker` (or its replacement) on Mac and Windows, I'm not sure how much longer it will make sense to try to have a working Docker volume driver for VirtualBox. Since that's the only reason I created this library in the first place and I don't have a more general need for a VBoxWebSrv API client in Go, it doesn't make much sense for me to make time to work on this library given my other priorities. Aside from the inability to issue commands from inside a VM, `VBoxManage` works quite well and fully supports all available VirtualBox APIs.

@clintonskitson I'm glad I was able to create something useful for you to use as a starting point. You and the rest of @emccode have done a great job with REX-Ray and I'm honored to have had a minor role in that success.

**Comment by blacktop** [comment]
@md5 yes, much thanks for getting this started.  I had just used [gowsdl](https://github.com/hooklift/gowsdl) on the vbox sdk and thought _'I wonder if anyone else thought of doing this'_ and that is how I found you.

So because you are not going to have time to work on this, do you think it makes sense for @clintonskitson to take it over?

My personal interest isn't in volumes, but in automating vbox from docker to control Windows VMs.  

I could also see @docker 's docker-machine using this as well as maybe @hashicorp using it with **vagrant**, as they are now moving toward dockerizing their product line.

**Comment by md5** [comment]
@blacktop I have no problem transferring this code if someone's interested in picking up the torch.

As for `gowsdl`, I had to enhance it in order to generate bindings for the `VBoxWebSrv` WSDL, so there's that lasting benefit too 👍

**Comment by blacktop** [comment]
@md5 that is awesome! Much thanks for your work on this as well as `gowsdl` ❤️

@clintonskitson do you want/have time to take over **go-virtualboxclient**?

Have either one of you messed with `IConsolepowerDown` it looks like you can't call it directly but have to via a session.console?

**Comment by clintkitson** [comment]
I could establish something for this. But question for you, this package was specifically needed because of the SOAP/remote interface capabilities. Meaning, REX-Ray runs inside of a VM in VirtualBox and actually is remotely talking to the underlying VirtualBox instance (living is OS X) via the SOAP API.  This seems more unique?

If the remotability isn't required then this may not be the approach that makes the most sense for you. If your use case is for an app running along side virtualbox then you could use the XPCOM API or the C bindings in Go. Make sense?

https://github.com/pwnall/vbox

**Comment by blacktop** [comment]
@clintonskitson remotability is the most important feature to me 😉 

I was going to have a RESTful proxy running on the host that would just exec commands to VirtualBox, which is very gross 😞  I need to orchestrate VirtualBox from inside docker inside VirtualBox.  To cut to the chase I am going to run Cuckoo in docker.  Cuckoo starts Windows VMs and detonates malware in them.  This project is the missing piece of the puzzle.  I would have done it with python, but ZSI is dead (supports py2.5 ???)  This is the only way I see forward without having to have my users run a dumb Go proxy binary on their host along with the docker containers running Cuckoo.  If you could help me get started on the banal features like: Start VM, Stop VM, dump pcap, dump RAM, I can help flesh out the rest of the SOAP API, knowing that you don't need it for REX-ray, but others might find it useful in the future as well?

**Comment by clintkitson** [comment]
Gotcha. We tend to be more focused on just the volumes stuff.

Well the WSDL is a full dump of the calls that are available. In order to figure out how to properly make calls for volumes I did look at other projects like the one that was written against the C bindings. These do tend to align very closely to the SOAP calls/methods being called.

**Comment by blacktop** [comment]
@md5 @clintonskitson Are you guys doing anything for vboxwebsrv other than running `vboxweb.wsdl` through **gowsdl**?  I just tried and got a file half as large as yours.

**Comment by md5** [comment]
@blacktop No, that's it. I know there are some differences between the different versions of VirtualBox.

Can you tell what's different about your file?

**Comment by blacktop** [comment]
521K May 21 19:18 vboxweb.go < ---mine
1.0M May 14 15:06 vboxwebsrv.go <--- yours from #2 

Also trying to run @clintonskitson code with an updated version of the SDK fails with the following:

``` bash
vboxapi/machine.go:16: undefined: vboxweb.ChipsetType
vboxapi/machine.go:17: undefined: vboxweb.IMachinegetChipsetType
vboxapi/machine.go:19: m.virtualbox.IMachinegetChipsetType undefined (type *VirtualBox has no field or method IMachinegetChipsetType)
vboxapi/machine.go:140: undefined: vboxweb.LockTypeShared
vboxapi/machine.go:171: unknown vboxweb.IMachineattachDevice field 'Medium' in struct literal
vboxapi/machine.go:194: undefined: vboxweb.LockTypeShared
vboxapi/machine.go:252: undefined: vboxweb.LockType
vboxapi/medium.go:25: cannot use logicalSize (type int64) as type uint64 in field value
vboxapi/session.go:21: undefined: vboxweb.LockType
vboxapi/system_properties.go:12: undefined: vboxweb.ChipsetType
vboxapi/medium.go:25: too many errors
```

So the version I made doesn't have things that for the most part the machine.go needs?

**Comment by blacktop** [comment]
@clintonskitson I have noticed that the version 5 of the API is missing things like `IMachine::lockMachine` etc are you adding it back in manually?

**Comment by blacktop** [comment]
these `vboxweb.wsdl` files are NUTS, they keep leaving stuff out that still works. It is like you have to mix 3 of them together to get a complete API, they really don't want people to use the SOAP api?? Probably giving all their love to the COM peeps 😢
